// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPywaFWOylJvYQCinCSMBp1HmqeryRno0',
    appId: '1:340727636000:web:8ac210778dc9af3c3c9c45',
    messagingSenderId: '340727636000',
    projectId: 'icemish-flutter',
    authDomain: 'icemish-flutter.firebaseapp.com',
    storageBucket: 'icemish-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdh2C_Ed2E_sN6WzkMh7sABCaOfJT1FtA',
    appId: '1:340727636000:android:d05d1c10b4d9d43b3c9c45',
    messagingSenderId: '340727636000',
    projectId: 'icemish-flutter',
    storageBucket: 'icemish-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX6mHSpHwBvtlcju8BmXxvbHhi1lcdaJ4',
    appId: '1:340727636000:ios:84e9be997c6c3e063c9c45',
    messagingSenderId: '340727636000',
    projectId: 'icemish-flutter',
    storageBucket: 'icemish-flutter.appspot.com',
    iosBundleId: 'com.example.icemish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX6mHSpHwBvtlcju8BmXxvbHhi1lcdaJ4',
    appId: '1:340727636000:ios:84e9be997c6c3e063c9c45',
    messagingSenderId: '340727636000',
    projectId: 'icemish-flutter',
    storageBucket: 'icemish-flutter.appspot.com',
    iosBundleId: 'com.example.icemish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPywaFWOylJvYQCinCSMBp1HmqeryRno0',
    appId: '1:340727636000:web:b228d703a39338033c9c45',
    messagingSenderId: '340727636000',
    projectId: 'icemish-flutter',
    authDomain: 'icemish-flutter.firebaseapp.com',
    storageBucket: 'icemish-flutter.appspot.com',
  );
}
